// Manual barrel mapping component id -> demo (spec §8.1 — no reflection, no
// codegen). Maintained by tools/new_component.dart, which inserts the import
// and the map entry in alphabetical order. Keep it sorted by id.

import 'package:snipz/components/additive_creature/additive_creature_demo.dart';
import 'package:snipz/components/animated_content/animated_content_demo.dart';
import 'package:snipz/components/aurora_stack/aurora_stack_demo.dart';
import 'package:snipz/components/before_after/before_after_demo.dart';
import 'package:snipz/components/bloub_bot/bloub_bot_demo.dart';
import 'package:snipz/components/blur_text/blur_text_demo.dart';
import 'package:snipz/components/bounce_cards/bounce_cards_demo.dart';
import 'package:snipz/components/bouncing_ball/bouncing_ball_demo.dart';
import 'package:snipz/components/breathing_orb/breathing_orb_demo.dart';
import 'package:snipz/components/calm_breath/calm_breath_demo.dart';
import 'package:snipz/components/calm_climb/calm_climb_demo.dart';
import 'package:snipz/components/calm_email/calm_email_demo.dart';
import 'package:snipz/components/calm_insights/calm_insights_demo.dart';
import 'package:snipz/components/calm_login/calm_login_demo.dart';
import 'package:snipz/components/calm_mood/calm_mood_demo.dart';
import 'package:snipz/components/calm_onboard/calm_onboard_demo.dart';
import 'package:snipz/components/calm_paywall/calm_paywall_demo.dart';
import 'package:snipz/components/calm_sleep/calm_sleep_demo.dart';
import 'package:snipz/components/calm_streak/calm_streak_demo.dart';
import 'package:snipz/components/calm_welcome/calm_welcome_demo.dart';
import 'package:snipz/components/card_resize/card_resize_demo.dart';
import 'package:snipz/components/choice_chips/choice_chips_demo.dart';
import 'package:snipz/components/claude_thinking/claude_thinking_demo.dart';
import 'package:snipz/components/confetti_burst/confetti_burst_demo.dart';
import 'package:snipz/components/contextual_dock/contextual_dock_demo.dart';
import 'package:snipz/components/copy_button/copy_button_demo.dart';
import 'package:snipz/components/dither/dither_demo.dart';
import 'package:snipz/components/dock/dock_demo.dart';
import 'package:snipz/components/drum_clock/drum_clock_demo.dart';
import 'package:snipz/components/ease_lab/ease_lab_demo.dart';
import 'package:snipz/components/elastic_lasso/elastic_lasso_demo.dart';
import 'package:snipz/components/elastic_slider/elastic_slider_demo.dart';
import 'package:snipz/components/equalizer_bars/equalizer_bars_demo.dart';
import 'package:snipz/components/error_shake/error_shake_demo.dart';
import 'package:snipz/components/expanding_search/expanding_search_demo.dart';
import 'package:snipz/components/faulty_terminal/faulty_terminal_demo.dart';
import 'package:snipz/components/firefly_swarm/firefly_swarm_demo.dart';
import 'package:snipz/components/flick_feed/flick_feed_demo.dart';
import 'package:snipz/components/flip_grid/flip_grid_demo.dart';
import 'package:snipz/components/float_bob/float_bob_demo.dart';
import 'package:snipz/components/fluid_glass/fluid_glass_demo.dart';
import 'package:snipz/components/glass_card/glass_card_demo.dart';
import 'package:snipz/components/gradient_shimmer_text/gradient_shimmer_text_demo.dart';
import 'package:snipz/components/gradient_text/gradient_text_demo.dart';
import 'package:snipz/components/gradient_waves/gradient_waves_demo.dart';
import 'package:snipz/components/gradual_blur/gradual_blur_demo.dart';
import 'package:snipz/components/grid_ripple/grid_ripple_demo.dart';
import 'package:snipz/components/hold_to_confirm/hold_to_confirm_demo.dart';
import 'package:snipz/components/hold_to_talk/hold_to_talk_demo.dart';
import 'package:snipz/components/inertia_throw/inertia_throw_demo.dart';
import 'package:snipz/components/infinite_menu/infinite_menu_demo.dart';
import 'package:snipz/components/irregular_typewriter/irregular_typewriter_demo.dart';
import 'package:snipz/components/jelly_blob/jelly_blob_demo.dart';
import 'package:snipz/components/lattice_snap/lattice_snap_demo.dart';
import 'package:snipz/components/like_burst/like_burst_demo.dart';
import 'package:snipz/components/line_drawing/line_drawing_demo.dart';
import 'package:snipz/components/marquee_reveal/marquee_reveal_demo.dart';
import 'package:snipz/components/momentum_picker/momentum_picker_demo.dart';
import 'package:snipz/components/morph_slider/morph_slider_demo.dart';
import 'package:snipz/components/neon_glow_pulse/neon_glow_pulse_demo.dart';
import 'package:snipz/components/notification_slide_in/notification_slide_in_demo.dart';
import 'package:snipz/components/option_wheel/option_wheel_demo.dart';
import 'package:snipz/components/orbit_spinner/orbit_spinner_demo.dart';
import 'package:snipz/components/orbital_action_menu/orbital_action_menu_demo.dart';
import 'package:snipz/components/page_peel/page_peel_demo.dart';
import 'package:snipz/components/particle_field/particle_field_demo.dart';
import 'package:snipz/components/pixel_blast/pixel_blast_demo.dart';
import 'package:snipz/components/pixel_card/pixel_card_demo.dart';
import 'package:snipz/components/pixel_loader/pixel_loader_demo.dart';
import 'package:snipz/components/pixel_transition/pixel_transition_demo.dart';
import 'package:snipz/components/pixel_walker/pixel_walker_demo.dart';
import 'package:snipz/components/pull_reveal_refresh/pull_reveal_refresh_demo.dart';
import 'package:snipz/components/radar_pulse/radar_pulse_demo.dart';
import 'package:snipz/components/rate_limit_cooldown/rate_limit_cooldown_demo.dart';
import 'package:snipz/components/reveal_list/reveal_list_demo.dart';
import 'package:snipz/components/scramble_text/scramble_text_demo.dart';
import 'package:snipz/components/scroll_expand/scroll_expand_demo.dart';
import 'package:snipz/components/shape_morph/shape_morph_demo.dart';
import 'package:snipz/components/shimmer_skeleton/shimmer_skeleton_demo.dart';
import 'package:snipz/components/signal_bars/signal_bars_demo.dart';
import 'package:snipz/components/signal_braille/signal_braille_demo.dart';
import 'package:snipz/components/skeleton_content/skeleton_content_demo.dart';
import 'package:snipz/components/skeleton_sweep/skeleton_sweep_demo.dart';
import 'package:snipz/components/snap_rail/snap_rail_demo.dart';
import 'package:snipz/components/spectrum_sweep/spectrum_sweep_demo.dart';
import 'package:snipz/components/speed_dial_fab/speed_dial_fab_demo.dart';
import 'package:snipz/components/split_flap_text/split_flap_text_demo.dart';
import 'package:snipz/components/star_border/star_border_demo.dart';
import 'package:snipz/components/starling_flock/starling_flock_demo.dart';
import 'package:snipz/components/step_progress/step_progress_demo.dart';
import 'package:snipz/components/stepper/stepper_demo.dart';
import 'package:snipz/components/switch_spring/switch_spring_demo.dart';
import 'package:snipz/components/tab_pill_glide/tab_pill_glide_demo.dart';
import 'package:snipz/components/tag_input/tag_input_demo.dart';
import 'package:snipz/components/text_type/text_type_demo.dart';
import 'package:snipz/components/toast_overshoot/toast_overshoot_demo.dart';
import 'package:snipz/components/toast_stack/toast_stack_demo.dart';
import 'package:snipz/components/true_focus/true_focus_demo.dart';
import 'package:snipz/components/typing_indicator/typing_indicator_demo.dart';
import 'package:snipz/components/undo_snackbar/undo_snackbar_demo.dart';
import 'package:snipz/components/variable_weight/variable_weight_demo.dart';
import 'package:snipz/components/vector_recall/vector_recall_demo.dart';
import 'package:snipz/components/wave_loader/wave_loader_demo.dart';
import 'package:snipz/core/component_demo.dart';

final Map<String, ComponentDemo> componentRegistry = <String, ComponentDemo>{
  'additive_creature': additiveCreatureDemo,
  'animated_content': animatedContentDemo,
  'aurora_stack': auroraStackDemo,
  'before_after': beforeAfterDemo,
  'bloub_bot': bloubBotDemo,
  'blur_text': blurTextDemo,
  'bounce_cards': bounceCardsDemo,
  'bouncing_ball': bouncingBallDemo,
  'breathing_orb': breathingOrbDemo,
  'calm_breath': calmBreathDemo,
  'calm_climb': calmClimbDemo,
  'calm_email': calmEmailDemo,
  'calm_insights': calmInsightsDemo,
  'calm_login': calmLoginDemo,
  'calm_mood': calmMoodDemo,
  'calm_onboard': calmOnboardDemo,
  'calm_paywall': calmPaywallDemo,
  'calm_sleep': calmSleepDemo,
  'calm_streak': calmStreakDemo,
  'calm_welcome': calmWelcomeDemo,
  'card_resize': cardResizeDemo,
  'choice_chips': choiceChipsDemo,
  'claude_thinking': claudeThinkingDemo,
  'confetti_burst': confettiBurstDemo,
  'contextual_dock': contextualDockDemo,
  'copy_button': copyButtonDemo,
  'dither': ditherDemo,
  'dock': dockDemo,
  'drum_clock': drumClockDemo,
  'ease_lab': easeLabDemo,
  'elastic_lasso': elasticLassoDemo,
  'elastic_slider': elasticSliderDemo,
  'equalizer_bars': equalizerBarsDemo,
  'error_shake': errorShakeDemo,
  'expanding_search': expandingSearchDemo,
  'faulty_terminal': faultyTerminalDemo,
  'firefly_swarm': fireflySwarmDemo,
  'flick_feed': flickFeedDemo,
  'flip_grid': flipGridDemo,
  'float_bob': floatBobDemo,
  'fluid_glass': fluidGlassDemo,
  'glass_card': glassCardDemo,
  'gradient_shimmer_text': gradientShimmerTextDemo,
  'gradient_text': gradientTextDemo,
  'gradient_waves': gradientWavesDemo,
  'gradual_blur': gradualBlurDemo,
  'grid_ripple': gridRippleDemo,
  'hold_to_confirm': holdToConfirmDemo,
  'hold_to_talk': holdToTalkDemo,
  'inertia_throw': inertiaThrowDemo,
  'infinite_menu': infiniteMenuDemo,
  'irregular_typewriter': irregularTypewriterDemo,
  'jelly_blob': jellyBlobDemo,
  'lattice_snap': latticeSnapDemo,
  'like_burst': likeBurstDemo,
  'line_drawing': lineDrawingDemo,
  'marquee_reveal': marqueeRevealDemo,
  'momentum_picker': momentumPickerDemo,
  'morph_slider': morphSliderDemo,
  'neon_glow_pulse': neonGlowPulseDemo,
  'notification_slide_in': notificationSlideInDemo,
  'option_wheel': optionWheelDemo,
  'orbit_spinner': orbitSpinnerDemo,
  'orbital_action_menu': orbitalActionMenuDemo,
  'page_peel': pagePeelDemo,
  'particle_field': particleFieldDemo,
  'pixel_blast': pixelBlastDemo,
  'pixel_card': pixelCardDemo,
  'pixel_loader': pixelLoaderDemo,
  'pixel_transition': pixelTransitionDemo,
  'pixel_walker': pixelWalkerDemo,
  'pull_reveal_refresh': pullRevealRefreshDemo,
  'radar_pulse': radarPulseDemo,
  'rate_limit_cooldown': rateLimitCooldownDemo,
  'reveal_list': revealListDemo,
  'scramble_text': scrambleTextDemo,
  'scroll_expand': scrollExpandDemo,
  'shape_morph': shapeMorphDemo,
  'shimmer_skeleton': shimmerSkeletonDemo,
  'signal_bars': signalBarsDemo,
  'signal_braille': signalBrailleDemo,
  'skeleton_content': skeletonContentDemo,
  'skeleton_sweep': skeletonSweepDemo,
  'snap_rail': snapRailDemo,
  'spectrum_sweep': spectrumSweepDemo,
  'speed_dial_fab': speedDialFabDemo,
  'split_flap_text': splitFlapTextDemo,
  'star_border': starBorderDemo,
  'starling_flock': starlingFlockDemo,
  'step_progress': stepProgressDemo,
  'stepper': stepperDemo,
  'switch_spring': switchSpringDemo,
  'tab_pill_glide': tabPillGlideDemo,
  'tag_input': tagInputDemo,
  'text_type': textTypeDemo,
  'toast_overshoot': toastOvershootDemo,
  'toast_stack': toastStackDemo,
  'true_focus': trueFocusDemo,
  'typing_indicator': typingIndicatorDemo,
  'undo_snackbar': undoSnackbarDemo,
  'variable_weight': variableWeightDemo,
  'vector_recall': vectorRecallDemo,
  'wave_loader': waveLoaderDemo,
};
